name: Playground

on:
  pull_request:
    branches:
      - master
  issue_comment:
    types: [created]

jobs:
  spitout:
    runs-on: ubuntu-18.04
    name: Check event and maybe build
    steps:
      - uses: actions/checkout@v1
      - name: Echo event
        run: |
          echo $GITHUB_EVENT_PATH
          jq .comment.body $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
      - name: Check if /qa was in comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if:  contains(github.event.comment.body, '/qa') == true
        run: |
          echo Build stuff NOW...
