name: Playground

on:
  issue_comment:
    types: [created]

jobs:
  spitout:
    runs-on: ubuntu-18.04
    name: Check event and maybe build
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/pull/${PULL_REQUEST_NUMBER}/merge
      - name: Echo event
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo $PULL_REQUEST_NUMBER
          echo $GITHUB_EVENT_PATH
          jq .comment.body $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
      - name: Check if /qa was in comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if:  contains(github.event.comment.body, '/qa') == true
        run: |
          echo Build stuff NOW...
          export PR_URL=`jq -r .issue.pull_request.url $GITHUB_EVENT_PATH`
          echo $PR_URL
