name: Playground

on:
  issue_comment:
    types: [created]

jobs:
  spitout:
    runs-on: ubuntu-18.04
    name: Check event and maybe build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
          with:
            ref: refs/pull/2/merge
        env:
          PULL_REQUEST_NUMBER: {{ github.event.comment.pull_request.number }}
        run: |
          echo $GITHUB_EVENT_PATH
          jq .comment.body $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
      - name: Check deploy command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if:  github.event.comment.body == 'deploy this please'
        run: |
          echo Build stuff NOW...
